# Generated by Django 2.2.5 on 2019-09-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190928_1645'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
    ]
