# Generated by Django 2.2.5 on 2019-09-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190928_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='color',
            field=models.CharField(max_length=50),
        ),
    ]
