# Generated by Django 2.2.5 on 2019-09-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20190928_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
