# Generated by Django 2.2.5 on 2019-09-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default=123, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
